<a href="https://colab.research.google.com/github/DorotaJanosz/data-science-bootcamp/blob/master/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

###Norma wektora i doległość punktów


In [0]:
v1 = np.array([2,5])

In [12]:
np.linalg.norm(v1) #norma wektora

5.385164807134504

In [0]:
v2 = np.array([2,5,9,13])

In [14]:
np.linalg.norm(v2)

16.703293088490067

In [0]:
p = np.array([3,0])
q = np.array([0,4])

In [16]:
np.linalg.norm(p-q) #odglełość dwóch punktów

5.0

In [0]:
p = np.array([2,5,9])
q = np.array([5,7,10])

In [19]:
np.linalg.norm(p-q)

3.7416573867739413

###Mnożenie macierzy

In [20]:
A = np.array([[5,3],[3,9]])
B = np.array([[1],[-1]])
print(A, "\n")
print(B)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [21]:
np.dot(A,B)

array([[ 2],
       [-6]])

In [22]:
X = np.array([[2,-1,3],[3,1,0]])
Y = np.array([[2,-1,1],[0,-1,2],[3,2,0]])
print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2 -1  1]
 [ 0 -1  2]
 [ 3  2  0]]


In [23]:
np.dot(X,Y)

array([[13,  5,  0],
       [ 6, -4,  5]])

###Wyznacznik macierzy

In [0]:
A = np.array([[2,4],[-1,3]])

In [26]:
np.linalg.det(A)

9.999999999999998

In [28]:
round(np.linalg.det(A))

10.0

###Ślad macierzy

In [0]:
A = np.array([[2,4],[5,6]])

In [32]:
np.trace(A) #Ślad maceirzy tu suma elementów na przekątnej


8

###Macierz jednostkowa

In [33]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

###Macierz odwrotna

In [0]:
A = np.array([[2,4],[-1,3]])

In [36]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

###Macierz transponowana

In [39]:
A = np.array([[2,4,5],[1,4,6]])
A

array([[2, 4, 5],
       [1, 4, 6]])

In [40]:
np.transpose(A)

array([[2, 1],
       [4, 4],
       [5, 6]])

In [41]:
A.T

array([[2, 1],
       [4, 4],
       [5, 6]])

###Rozwiązywanie ukladów równań

In [45]:
A = np.array([[2,4],[1,-1]])
A

array([[ 2,  4],
       [ 1, -1]])

In [46]:
X = np.array([10,-1])
X

array([10, -1])

In [47]:
B = np.array([[10],[-1]])
B

array([[10],
       [-1]])

In [0]:
A_inv = np.linalg.inv(A)

In [49]:
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])