<a href="https://colab.research.google.com/github/DorotaJanosz/data-science-bootcamp/blob/master/01/wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

###Podstawy


In [2]:
np.__version__

'1.18.3'

In [0]:
dir(np)

In [0]:
help(np.array)

In [9]:
x = np.array([1,3])
print(x)

[1 3]


In [10]:
type(x)

numpy.ndarray

In [12]:
x.ndim

1

In [13]:
x.shape

(2,)

In [14]:
x.size

2

In [15]:
x.dtype

dtype('int64')

In [18]:
y = np.array([1.2, 2.5, 3.6])
y


array([1.2, 2.5, 3.6])

In [19]:
y.dtype

dtype('float64')

In [24]:
x = np.array([[1,2],[-3,4]])
print(x)

[[ 1  2]
 [-3  4]]


In [25]:
x.shape

(2, 2)

In [28]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
x.shape

(2, 3)

In [34]:
x = np.array(
    [
     [[4,3,2],
      [4,5,6]],
     
     [[1,2,3],
      [7,8,9]],

      [[4,5,6],
       [7,9,0]]
     ]    
)
x

array([[[4, 3, 2],
        [4, 5, 6]],

       [[1, 2, 3],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 9, 0]]])

In [35]:
x.shape

(3, 2, 3)

In [36]:
x.ndim

3

###Tworzenie tablic


In [39]:
x = np.zeros(shape = (4,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
np.ones(shape=(5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.full(shape=(3,3), fill_value=4)

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [43]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [45]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [47]:
np.arange(start = 100, stop = 10, step= -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [49]:
np.arange(0,1,0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [50]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [0]:
a = np.arange(15)

In [54]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [55]:
a.reshape(5,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [56]:
a.reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###Podstawowe operacje na tablicach

In [57]:
A = np.array([2,3,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[2 3 4 2]
[ 3 -1  3  2]


In [58]:
A + B

array([5, 2, 7, 4])

In [65]:
np.add(A,B)

array([5, 2, 7, 4])

In [59]:
A - B

array([-1,  4,  1,  0])

In [66]:
np.subtract(A,B)

array([-1,  4,  1,  0])

In [60]:
A * B

array([ 6, -3, 12,  4])

In [67]:
np.multiply(A,B)

array([ 6, -3, 12,  4])

In [61]:
A / B

array([ 0.66666667, -3.        ,  1.33333333,  1.        ])

In [68]:
np.divide(A,B)

array([ 0.66666667, -3.        ,  1.33333333,  1.        ])

In [62]:
A + 3

array([5, 6, 7, 5])

In [63]:
2 * A


array([4, 6, 8, 4])

In [64]:
A + 3*B

array([11,  0, 13,  8])

In [72]:
X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [73]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [77]:
X @ Y

array([[  3,   6],
       [-12,   0]])

In [74]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [75]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

###Generowanie liczb pseudolosowych

In [0]:
np.random.seed(0)

In [86]:
np.random.randn(10)

array([ 0.8644362 , -0.74216502,  2.26975462, -1.45436567,  0.04575852,
       -0.18718385,  1.53277921,  1.46935877,  0.15494743,  0.37816252])

In [92]:
np.random.randn(10,4)

array([[ 1.04502338,  0.59903953, -0.34069234, -1.26317291],
       [-2.77735915,  1.15173397, -0.58922899, -0.44846501],
       [ 0.13157397, -1.40556005, -0.34978218,  2.02347195],
       [ 0.50538694,  0.35924916, -1.58249448,  2.24360189],
       [-1.42279491,  1.92232476, -2.11505602,  1.40536544],
       [ 1.61805427, -0.82440912,  0.42258037,  0.54748057],
       [-0.81379448, -1.44911761, -1.31771734,  0.54100822],
       [-0.0851156 , -0.56430103,  0.96676801,  0.50806791],
       [-0.75546273, -1.20120152,  0.52326174, -0.53758337],
       [ 0.09920486,  1.57629897,  0.50232824, -0.862267  ]])

In [96]:
np.random.rand(10,2)

array([[0.88432423, 0.95853234],
       [0.20751273, 0.78846839],
       [0.27334874, 0.88713154],
       [0.16554561, 0.66595992],
       [0.08421126, 0.97389332],
       [0.70063334, 0.84181574],
       [0.56666934, 0.47680136],
       [0.62188239, 0.52874151],
       [0.46938436, 0.75945025],
       [0.17820095, 0.17117205]])

In [98]:
np.random.randint(10)

1

In [100]:
np.random.randint(low=10, high = 100, size = 20)

array([21, 25, 35, 31, 32, 91, 82, 40, 51, 19, 62, 53, 91, 60, 26, 74, 36,
       17, 64, 92])

In [101]:
np.random.choice([1,5,19,18,15])

19

In [103]:
np.random.choice(["java","python","sql"])

'python'

In [106]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
np.random.shuffle(data)
data

array([9, 4, 6, 2, 8, 7, 0, 5, 3, 1])

###Podstawowe funkcje w bibliotece NumPy

In [110]:
np.exp(1)

2.718281828459045

In [111]:
np.exp(3)

20.085536923187668

In [112]:
np.sqrt(9)

3.0

In [113]:
np.all([1,5,10])

True

In [114]:
np.any([0,1,0])

True

In [116]:
A = np.random.rand(10)
A

array([0.46573156, 0.62667545, 0.2662897 , 0.20863952, 0.44840682,
       0.25062143, 0.85260936, 0.05846388, 0.28915337, 0.17765174])

In [117]:
np.argmax(A)

6

In [118]:
A[np.argmax(A)]

0.8526093568201201

In [119]:
np.argmin(A)

7

In [120]:
np.argsort(A)

array([7, 9, 3, 5, 2, 8, 4, 0, 1, 6])

In [121]:
np.max(A)

0.8526093568201201

In [122]:
np.min(A)

0.05846387868409442

In [123]:
np.mean(A)

0.3644242821869633

In [124]:
np.median(A)

0.2777215379958727

In [125]:
np.std(A)

0.22481735053318735

###Indeksowanie i wycinanie tablic

In [129]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
A[2]

2

In [131]:
A[:2]

array([0, 1])

In [132]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [135]:
A[[0,2]]

array([0, 2])

In [136]:
A[-1]

19

In [139]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [140]:
A[1]

array([5, 6, 7, 8, 9])

In [141]:
A[:,0]

array([ 0,  5, 10, 15])

In [142]:
A[:,-1]

array([ 4,  9, 14, 19])

In [143]:
A[1,1]

6

In [145]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [147]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

###Iteracja po tablicach, zmiana rozmiaru

In [148]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [150]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [152]:
for row in A:
  print(row[0])

0
5
10
15


In [154]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [158]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [159]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

###Maski logiczne

In [0]:
A = np.arange(-10,10,0.5)

In [162]:
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [163]:
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [164]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [166]:
np.bitwise_and(A>-5, A<5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [167]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [169]:
A[(A>-5) & (A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [170]:
np.bitwise_or(A<-5, A>5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [174]:
(A<-5) | (A>5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])